/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;

/**
 *
 * @author Rafael
 */
public class Vista extends javax.swing.JFrame {

    Controlador controlador;
    
    /**
     * Creates new form vista
     */
    public Vista() {
        controlador= new Controlador (this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGeneral = new javax.swing.JTabbedPane();
        Club = new javax.swing.JPanel();
        crearClub = new javax.swing.JButton();
        modificarClub = new javax.swing.JButton();
        eliminarClub = new javax.swing.JButton();
        labelClub = new javax.swing.JLabel();
        labelEstadio = new javax.swing.JLabel();
        labelCreacion = new javax.swing.JLabel();
        jtextClub = new javax.swing.JTextField();
        jtextEstadio = new javax.swing.JTextField();
        jtextCreacion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClubes = new javax.swing.JTable();
        futbolistaClub = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaClubFutbolista = new javax.swing.JTable();
        jtextIdClub = new javax.swing.JTextField();
        borrarClub = new javax.swing.JButton();
        Futbolistas = new javax.swing.JPanel();
        modificarFutbolista = new javax.swing.JButton();
        eliminarFutbolista = new javax.swing.JButton();
        labelNIF = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelNacimiento = new javax.swing.JLabel();
        labelNacionalidad = new javax.swing.JLabel();
        jtextNIF = new javax.swing.JTextField();
        jtextNombre = new javax.swing.JTextField();
        jtextNacimiento = new javax.swing.JTextField();
        jtextNacionalidad = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaFutbolistas = new javax.swing.JTable();
        crearFutbolista = new javax.swing.JButton();
        clubFutbolista = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaFutbolistaClub = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jtextApellido = new javax.swing.JTextField();
        jtextIdFutbolista = new javax.swing.JTextField();
        borrarFutbolista = new javax.swing.JButton();
        Relacion = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaClubR = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaFutbolistaR = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtextTemporada = new javax.swing.JTextField();
        botonRelacion = new javax.swing.JButton();
        jtextFutbolistaR = new javax.swing.JTextField();
        jtextClubR = new javax.swing.JTextField();
        jtextIDFR = new javax.swing.JTextField();
        jtextIDCR = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        tablaRelacion = new javax.swing.JTable();
        borrarRelacion = new javax.swing.JToggleButton();
        eliminarRelacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        crearClub.setText("Crear");
        crearClub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearClubActionPerformed(evt);
            }
        });

        modificarClub.setText("Modificar");

        eliminarClub.setText("Eliminar");

        labelClub.setText("Nombre:");

        labelEstadio.setText("Estadio:");

        labelCreacion.setText("Creación:");

        jtextClub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextClubActionPerformed(evt);
            }
        });

        jtextEstadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextEstadioActionPerformed(evt);
            }
        });

        jtextCreacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextCreacionActionPerformed(evt);
            }
        });

        tablaClubes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaClubes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaClubesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaClubes);

        futbolistaClub.setText("Futbolista");

        tablaClubFutbolista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablaClubFutbolista);

        jtextIdClub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextIdClubActionPerformed(evt);
            }
        });

        borrarClub.setText("Borrar");

        javax.swing.GroupLayout ClubLayout = new javax.swing.GroupLayout(Club);
        Club.setLayout(ClubLayout);
        ClubLayout.setHorizontalGroup(
            ClubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClubLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ClubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ClubLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ClubLayout.createSequentialGroup()
                        .addGroup(ClubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ClubLayout.createSequentialGroup()
                                .addComponent(labelCreacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtextCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ClubLayout.createSequentialGroup()
                                .addComponent(labelEstadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtextEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ClubLayout.createSequentialGroup()
                                .addComponent(labelClub)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtextClub, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)
                        .addComponent(futbolistaClub))
                    .addGroup(ClubLayout.createSequentialGroup()
                        .addGroup(ClubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtextIdClub, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ClubLayout.createSequentialGroup()
                                .addComponent(crearClub)
                                .addGap(18, 18, 18)
                                .addComponent(modificarClub)))
                        .addGap(18, 18, 18)
                        .addComponent(eliminarClub)
                        .addGap(18, 18, 18)
                        .addComponent(borrarClub)))
                .addContainerGap(341, Short.MAX_VALUE))
        );
        ClubLayout.setVerticalGroup(
            ClubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClubLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ClubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificarClub)
                    .addComponent(crearClub)
                    .addComponent(eliminarClub)
                    .addComponent(borrarClub))
                .addGap(11, 11, 11)
                .addComponent(jtextIdClub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ClubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelClub)
                    .addComponent(jtextClub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(futbolistaClub))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ClubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEstadio)
                    .addComponent(jtextEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ClubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCreacion)
                    .addComponent(jtextCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(ClubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        panelGeneral.addTab("Clubes", Club);

        modificarFutbolista.setText("Modificar");
        modificarFutbolista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarFutbolistaActionPerformed(evt);
            }
        });

        eliminarFutbolista.setText("Eliminar");

        labelNIF.setText("NIF:");

        labelNombre.setText("Nombre:");

        labelNacimiento.setText("Nacimiento:");

        labelNacionalidad.setText("Nacionalidad:");

        jtextNIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextNIFActionPerformed(evt);
            }
        });

        jtextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextNombreActionPerformed(evt);
            }
        });

        jtextNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextNacimientoActionPerformed(evt);
            }
        });

        tablaFutbolistas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaFutbolistas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaFutbolistasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaFutbolistas);

        crearFutbolista.setText("Crear");
        crearFutbolista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearFutbolistaActionPerformed(evt);
            }
        });

        clubFutbolista.setText("Club");

        tablaFutbolistaClub.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tablaFutbolistaClub);

        jLabel1.setText("Apellidos:");

        jtextApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextApellidoActionPerformed(evt);
            }
        });

        borrarFutbolista.setText("Borrar");

        javax.swing.GroupLayout FutbolistasLayout = new javax.swing.GroupLayout(Futbolistas);
        Futbolistas.setLayout(FutbolistasLayout);
        FutbolistasLayout.setHorizontalGroup(
            FutbolistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FutbolistasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FutbolistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FutbolistasLayout.createSequentialGroup()
                        .addGroup(FutbolistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FutbolistasLayout.createSequentialGroup()
                                .addComponent(crearFutbolista)
                                .addGap(18, 18, 18)
                                .addComponent(modificarFutbolista)
                                .addGap(29, 29, 29)
                                .addComponent(eliminarFutbolista)
                                .addGap(18, 18, 18)
                                .addComponent(borrarFutbolista))
                            .addGroup(FutbolistasLayout.createSequentialGroup()
                                .addComponent(labelNacionalidad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtextNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FutbolistasLayout.createSequentialGroup()
                                .addComponent(labelNacimiento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtextNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FutbolistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(FutbolistasLayout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(jtextApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(FutbolistasLayout.createSequentialGroup()
                                    .addGroup(FutbolistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelNIF)
                                        .addComponent(labelNombre))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(FutbolistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(FutbolistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jtextIdFutbolista, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtextNIF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))))))
                        .addGap(0, 738, Short.MAX_VALUE))
                    .addGroup(FutbolistasLayout.createSequentialGroup()
                        .addGroup(FutbolistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FutbolistasLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FutbolistasLayout.createSequentialGroup()
                                .addGap(223, 223, 223)
                                .addComponent(clubFutbolista)))
                        .addContainerGap(342, Short.MAX_VALUE))))
        );
        FutbolistasLayout.setVerticalGroup(
            FutbolistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FutbolistasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FutbolistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificarFutbolista)
                    .addComponent(eliminarFutbolista)
                    .addComponent(crearFutbolista)
                    .addComponent(borrarFutbolista))
                .addGap(8, 8, 8)
                .addComponent(jtextIdFutbolista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FutbolistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtextNIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNIF))
                .addGap(18, 18, 18)
                .addGroup(FutbolistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FutbolistasLayout.createSequentialGroup()
                        .addGroup(FutbolistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelNombre)
                            .addComponent(jtextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(FutbolistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtextApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addComponent(clubFutbolista))
                .addGap(18, 18, 18)
                .addGroup(FutbolistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNacimiento)
                    .addComponent(jtextNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FutbolistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelNacionalidad)
                    .addComponent(jtextNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(FutbolistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        panelGeneral.addTab("Futbolistas", Futbolistas);

        tablaClubR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaClubR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaClubRMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tablaClubR);

        tablaFutbolistaR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaFutbolistaR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaFutbolistaRMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tablaFutbolistaR);

        jLabel2.setText("Futbolista:");

        jLabel3.setText("Club:");

        jLabel4.setText("Temporada:");

        jtextTemporada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextTemporadaActionPerformed(evt);
            }
        });

        botonRelacion.setText("Relacionar");

        jtextClubR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextClubRActionPerformed(evt);
            }
        });

        jtextIDCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextIDCRActionPerformed(evt);
            }
        });

        tablaRelacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaRelacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaRelacionMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tablaRelacion);

        borrarRelacion.setText("Borrar");

        eliminarRelacion.setText("Eliminar");

        javax.swing.GroupLayout RelacionLayout = new javax.swing.GroupLayout(Relacion);
        Relacion.setLayout(RelacionLayout);
        RelacionLayout.setHorizontalGroup(
            RelacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, RelacionLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RelacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtextIDFR)
                    .addComponent(jtextFutbolistaR, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RelacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtextIDCR)
                    .addComponent(jtextClubR, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtextTemporada, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(botonRelacion)
                .addGap(13, 13, 13)
                .addComponent(eliminarRelacion)
                .addGap(18, 18, 18)
                .addComponent(borrarRelacion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(RelacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );
        RelacionLayout.setVerticalGroup(
            RelacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RelacionLayout.createSequentialGroup()
                .addGroup(RelacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RelacionLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jtextIDFR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RelacionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jtextIDCR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RelacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jtextTemporada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonRelacion)
                    .addComponent(jtextFutbolistaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtextClubR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrarRelacion)
                    .addComponent(eliminarRelacion))
                .addGap(40, 40, 40)
                .addGroup(RelacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        panelGeneral.addTab("Relacion", Relacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 1081, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtextNIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextNIFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextNIFActionPerformed

    private void jtextNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextNacimientoActionPerformed

    private void jtextClubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextClubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextClubActionPerformed

    private void jtextEstadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextEstadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextEstadioActionPerformed

    private void crearFutbolistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearFutbolistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearFutbolistaActionPerformed

    private void crearClubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearClubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearClubActionPerformed

    private void modificarFutbolistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarFutbolistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarFutbolistaActionPerformed

    private void jtextApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextApellidoActionPerformed

    private void tablaFutbolistasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaFutbolistasMouseClicked
        
        controlador.TablaFutbolistas(evt);
    }//GEN-LAST:event_tablaFutbolistasMouseClicked

    private void tablaClubesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClubesMouseClicked
        controlador.TablaClubes(evt);
    }//GEN-LAST:event_tablaClubesMouseClicked

    private void jtextCreacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextCreacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextCreacionActionPerformed

    private void jtextIdClubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextIdClubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextIdClubActionPerformed

    private void jtextTemporadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextTemporadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextTemporadaActionPerformed

    private void jtextClubRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextClubRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextClubRActionPerformed

    private void jtextIDCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextIDCRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextIDCRActionPerformed

    private void tablaFutbolistaRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaFutbolistaRMouseClicked
        // TODO add your handling code here:
        controlador.TablaFutbolistasR(evt);
    }//GEN-LAST:event_tablaFutbolistaRMouseClicked

    private void tablaClubRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClubRMouseClicked
        // TODO add your handling code here:
        controlador.TablaClubesR(evt);
    }//GEN-LAST:event_tablaClubRMouseClicked

    private void tablaRelacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaRelacionMouseClicked
        // TODO add your handling code here:
        controlador.TablaRelacion(evt);
    }//GEN-LAST:event_tablaRelacionMouseClicked

    private void jtextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Club;
    private javax.swing.JPanel Futbolistas;
    private javax.swing.JPanel Relacion;
    public javax.swing.JButton borrarClub;
    public javax.swing.JButton borrarFutbolista;
    public javax.swing.JToggleButton borrarRelacion;
    public javax.swing.JButton botonRelacion;
    public javax.swing.JButton clubFutbolista;
    public javax.swing.JButton crearClub;
    public javax.swing.JButton crearFutbolista;
    public javax.swing.JButton eliminarClub;
    public javax.swing.JButton eliminarFutbolista;
    public javax.swing.JButton eliminarRelacion;
    public javax.swing.JButton futbolistaClub;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    public javax.swing.JTextField jtextApellido;
    public javax.swing.JTextField jtextClub;
    public javax.swing.JTextField jtextClubR;
    public javax.swing.JTextField jtextCreacion;
    public javax.swing.JTextField jtextEstadio;
    public javax.swing.JTextField jtextFutbolistaR;
    public javax.swing.JTextField jtextIDCR;
    public javax.swing.JTextField jtextIDFR;
    public javax.swing.JTextField jtextIdClub;
    public javax.swing.JTextField jtextIdFutbolista;
    public javax.swing.JTextField jtextNIF;
    public javax.swing.JTextField jtextNacimiento;
    public javax.swing.JTextField jtextNacionalidad;
    public javax.swing.JTextField jtextNombre;
    public javax.swing.JTextField jtextTemporada;
    private javax.swing.JLabel labelClub;
    private javax.swing.JLabel labelCreacion;
    private javax.swing.JLabel labelEstadio;
    private javax.swing.JLabel labelNIF;
    private javax.swing.JLabel labelNacimiento;
    private javax.swing.JLabel labelNacionalidad;
    private javax.swing.JLabel labelNombre;
    public javax.swing.JButton modificarClub;
    public javax.swing.JButton modificarFutbolista;
    private javax.swing.JTabbedPane panelGeneral;
    public javax.swing.JTable tablaClubFutbolista;
    public javax.swing.JTable tablaClubR;
    public javax.swing.JTable tablaClubes;
    public javax.swing.JTable tablaFutbolistaClub;
    public javax.swing.JTable tablaFutbolistaR;
    public javax.swing.JTable tablaFutbolistas;
    public javax.swing.JTable tablaRelacion;
    // End of variables declaration//GEN-END:variables
}
